name: LobbyGUI-Plugin
version: '0.1.1'
main: janhelbling.jansmod.Jansmod
api-version: 1.17
authors: [ Jan, Thomas ]
description: LobbyPlugin für den besten Minecraft-Server - Bad Timing
commands:
  navigation:
    usage: /navigation
    description: Holt den Navigations-Kompass ins Inventar
  install-warp-db:
    usage: /install-1337
    description: Installiert MySQL DatenBank
    permission: jhinstall.warp
    permission-message: Kannst du nicht benutzen

permissions:
  jhinstall.warp:
    description: Installiere Warp-DB
    default: op

