#!/bin/bash

INSTALL=`which dialog`

if [ ! -f "$INSTALL" ]; then
        echo -n "Um $DATEI nutzen zu können, wird \"dialog\" aus den Paketquellen benötigt!\"dialog\" jetzt installiert? [ ja/nein ] "
        read frage

        if [ "$frage" = "ja" ]; then
                echo "installiere ..."
                sudo aptitude install -y dialog
        else
                echo "Abbruch"
                exit 0;
        fi;
fi;



if [ -f /root/.my.cnf ]; then
        echo "Datei Exestiert";	
else
	echo "Please enter root user MySQL password!";
        read -p dbuser;
	echo "Note: password will be hidden when typing";
	read -s passwd;
        echo -e "[client]" >> /root/.my.cnf;
	echo -e "user=$dbuser\npasswd=$passwd" >> /root/.my.cnf;
        exit;
fi

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="MYSQL Administrator"
TITLE="Menue"
MENU="Waehle aus folgenden Optionen:"

OPTIONS=(1 "Benutzer auflisten"
         2 "Datenbankenauflisten"
         3 "Datenbank erstellen, Benutzer wird mit erstellt"
         4 "Benutzer Loeschen"
         5 "Datenbank Loeschen")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose Option 1"
            mysql -e "SELECT user FROM mysql.user; /*\!40100 DEFAULT CHARACTER SET utf8 */;"
            ;;
        2)
            echo "You chose Option 2"
            mysql -e "SHOW DATABASES; /*\!40100 DEFAULT CHARACTER SET utf8 */;"
            ;;
        3)
            echo "You chose Option 3"
            echo "Enter database name!"
	    read dbname
    
	    echo "Creating new MySQL database..."
	    mysql -e "CREATE DATABASE ${dbname} /*\!40100 DEFAULT CHARACTER SET utf8 */;"
	    echo "Database successfully created!"
	
	    echo "Enter database user!"
	    read username
    
	    echo "Enter the PASSWORD for database user!"
	    echo "Note: password will be hidden when typing"
	    read -s userpass
    
	    echo "Creating new user..."
	    mysql -e "CREATE USER ${username}@localhost IDENTIFIED BY '${userpass}';"
	    echo "User successfully created!"

	    echo "Granting ALL privileges on ${dbname} to ${username}!"
	    mysql -e "GRANT ALL PRIVILEGES ON ${dbname}.* TO '${username}'@'localhost';"
	    mysql -e "FLUSH PRIVILEGES;"
            ;;
        4)
            echo "You chose Option 4"
            mysql -e "SELECT user FROM mysql.user; /*\!40100 DEFAULT CHARACTER SET utf8 */;"
            echo "Welcher Benutzer soll gelöscht werden: ";
            read user
            echo "Möchten Sie fortfahren? (Ja/Nein)? ";
            read antwort
            case $antwort in
                 ja|Ja)
                     echo "Ja";
                     mysql -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '$user'@'localhost'; /*\!40100 DEFAULT CHARACTER SET utf8 */;"
                     echo "Dem Benutzer $user wurden alle Rechte entzogen";
                     mysql -e "DROP USER '$user'@'localhost'; /*\!40100 DEFAULT CHARACTER SET utf8 */;"
                     echo "Benutzer $user wurde gelöscht";
                 ;;
                 nein/Nein)
                     echo "Nein";
                     exit
                 ;;
            esac
            ;;
        5)
            echo "You chose Option 5"
            mysql -e "SHOW DATABASES; /*\!40100 DEFAULT CHARACTER SET utf8 */;"
            echo "Welche Datenbank soll gelöscht werden: ";
            read db 
            echo "Möchten Sie fortfahren? (Ja/Nein)? ";
            read antwort
            case $antwort in
                 ja|Ja)
                     echo "Ja";
                     mysql -e "DROP DATABASE $db /*\!40100 DEFAULT CHARACTER SET utf8 */;"
                     echo "Datenbank $db wurde gelöscht";
                 ;;
                 nein|Nein)
                     echo "Nein";
                     exit
                 ;;
            esac
            ;;
esac