name: LobbyGUI-Plugin
version: '${project.version}'
main: janhelbling.jansmod.Jansmod
api-version: 1.17
authors: [ Jan, Thomas ]
description: LobbyPlugin für den besten Minecraft-Server - Bad Timing
commands:
  navigation:
    usage: /navigation
    description: Holt den Navigations-Kompass ins Inventar
  disablewarp:
    usage: /disbalewarp <name>
    description: Warp deaktivieren
  deletewarp:
    usage: /deletewarp <name>
    description: Warp löschen
  enablewarp:
    usage: /enablewarp <name>
    description: Warp löschen
  listwarp:
    usage: /listwarp
    description: Warps auflisten
  install-1337:
    usage: /install-1337
    description: Installiert MySQL DatenBank
